theme: jekyll-theme-cayman
title: Mustafa Ozkoc
description: >-
  Staff Research Engineer at Samsung Research America | 5G NR & 6G Researcher | Ph.D. NYU
  <br>
  ozkoc[at]mustafaozkoc.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Custom variables
github:
  is_project_page: false
