theme: jekyll-theme-cayman
title: Mustafa Ozkoc
description: >-
  Senior Research Engineer | Ph.D. from NYU
  <br>
  ozkoc[at]mustafaozkoc.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Custom variables
github:
  is_project_page: false
