header_pages:
  - index.markdown
  - Publications.markdown
  - Resume.markdown
  - Contact.markdown


title: Mustafa Ozkoc
email: ozkoc[at]nyu.edu

theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
